/* Copyright (c) Microsoft Corporation. Licensed under the MIT License. */

// Internal API dependencies only. No upstream views, actions, onboarding or agents.

import '../../browserView/browser/browserView.contribution.js';
import '../../chat/browser/aiCustomization/customizationHarnessService.js';
import '../../chat/browser/chatSessions/chatSessions.contribution.js';
import { AgentHostImportConversationStore, IAgentHostImportConversationStore } from '../../chat/browser/agentSessions/agentHost/agentHostImportConversationStore.js';
import { AgentNetworkFilterService, IAgentNetworkFilterService } from '../../../../platform/networkFilter/common/networkFilterService.js';
import { AgentPluginRepositoryService } from '../../chat/browser/agentPluginRepositoryService.js';
import { AgentPluginService } from '../../chat/common/plugins/agentPluginServiceImpl.js';
import { AgentSessionsService, IAgentSessionsService } from '../../chat/browser/agentSessions/agentSessionsService.js';
import { BrowserMcpGatewayService } from '../../mcp/browser/mcpGatewayService.js';
import { BrowserPluginGitCommandService } from '../../chat/browser/pluginGitCommandService.js';
import { ChatAccessibilityService } from '../../chat/browser/accessibility/chatAccessibilityService.js';
import { ChatAgentNameService, ChatAgentService, IChatAgentNameService, IChatAgentService } from '../../chat/common/participants/chatAgents.js';
import { ChatArtifactsService, IChatArtifactsService } from '../../chat/common/tools/chatArtifactsService.js';
import { ChatAttachmentResolveService, IChatAttachmentResolveService } from '../../chat/browser/attachments/chatAttachmentResolveService.js';
import { ChatAttachmentWidgetRegistry, IChatAttachmentWidgetRegistry } from '../../chat/browser/attachments/chatAttachmentWidgetRegistry.js';
import { ChatCodeBlockContextProviderService } from '../../chat/browser/codeBlockContextProviderService.js';
import { ChatContextPickService, IChatContextPickService } from '../../chat/browser/attachments/chatContextPickService.js';
import { ChatDebugServiceImpl } from '../../chat/common/chatDebugServiceImpl.js';
import { ChatEditingService } from '../../chat/browser/chatEditing/chatEditingServiceImpl.js';
import { ChatGoalSummaryService, IChatGoalSummaryService } from '../../chat/browser/chatGoalSummaryService.js';
import { ChatImageCarouselService, IChatImageCarouselService } from '../../chat/browser/chatImageCarouselService.js';
import { ChatLayoutService } from '../../chat/browser/widget/chatLayoutService.js';
import { ChatMarkdownAnchorService, IChatMarkdownAnchorService } from '../../chat/browser/widget/chatContentParts/chatMarkdownAnchorService.js';
import { ChatModeService, IChatModeService } from '../../chat/common/chatModes.js';
import { ChatModelFeedbackSurveyService, IChatModelFeedbackSurveyService } from '../../chat/browser/feedbackSurvey/chatModelFeedbackSurveyService.js';
import { ChatOutputRendererService, IChatOutputRendererService } from '../../chat/browser/chatOutputItemRenderer.js';
import { ChatPasteTargetService } from '../../chat/browser/attachments/chatPasteTargetService.js';
import { ChatPetService, IChatPetService } from '../../chat/browser/chatPetService.js';
import { ChatPetWidgetService, IChatPetWidgetService } from '../../chat/browser/widget/chatPetWidgetService.js';
import { ChatRequestOriginService, IChatRequestOriginService } from '../../chat/common/chatRequestOrigin.js';
import { ChatResponseResourceFileSystemProvider, IChatResponseResourceFileSystemProvider } from '../../chat/common/widget/chatResponseResourceFileSystemProvider.js';
import { ChatService } from '../../chat/common/chatService/chatServiceImpl.js';
import { ChatSideChatService, IChatSideChatService } from '../../chat/common/chatSideChatService.js';
import { ChatSlashCommandService, IChatSlashCommandService } from '../../chat/common/participants/chatSlashCommands.js';
import { ChatSpeechToTextService, IChatSpeechToTextService } from '../../chat/browser/speechToText/chatSpeechToTextService.js';
import { ChatSubmitRequestHandlerService, IChatSubmitRequestHandlerService } from '../../chat/browser/chatSubmitRequestHandlerService.js';
import { ChatTipService, IChatTipService } from '../../chat/browser/chatTipService.js';
import { ChatTodoListService, IChatTodoListService } from '../../chat/common/tools/chatTodoListService.js';
import { ChatToolRiskAssessmentService, IChatToolRiskAssessmentService } from '../../chat/browser/tools/chatToolRiskAssessmentService.js';
import { ChatTransferService, IChatTransferService } from '../../chat/common/model/chatTransferService.js';
import { ChatVariablesService } from '../../chat/browser/attachments/chatVariables.js';
import { ChatWidgetHistoryService, IChatWidgetHistoryService } from '../../chat/common/widget/chatWidgetHistoryService.js';
import { ChatWidgetService } from '../../chat/browser/widget/chatWidgetService.js';
import { CodeMapperService, ICodeMapperService } from '../../chat/common/editing/chatCodeMapperService.js';
import { CustomizationMigrationService } from '../../chat/browser/aiCustomization/customizationMigrationServiceImpl.js';
import { EditorChatResponseFileChangesService } from '../../chat/browser/editorChatResponseFileChangesService.js';
import { ExtensionRecommendationNotificationService } from '../../extensions/browser/extensionRecommendationNotificationService.js';
import { ExtensionRecommendationsService } from '../../extensions/browser/extensionRecommendationsService.js';
import { ExtensionsWorkbenchService } from '../../extensions/browser/extensionsWorkbenchService.js';
import { IAgentPluginRepositoryService } from '../../chat/common/plugins/agentPluginRepositoryService.js';
import { IAgentPluginService } from '../../chat/common/plugins/agentPluginService.js';
import { IChatAccessibilityService, IChatCodeBlockContextProviderService, IChatPasteTargetService, IChatWidgetService, IQuickChatService } from '../../chat/browser/chat.js';
import { IChatDebugService } from '../../chat/common/chatDebugService.js';
import { IChatEditingService } from '../../chat/common/editing/chatEditingService.js';
import { IChatLayoutService } from '../../chat/common/widget/chatLayoutService.js';
import { IChatResponseFileChangesService } from '../../chat/browser/chatResponseFileChangesService.js';
import { IChatService } from '../../chat/common/chatService/chatService.js';
import { IChatVariablesService } from '../../chat/common/attachments/chatVariables.js';
import { ICustomizationMigrationService } from '../../chat/common/promptSyntax/service/customizationMigrationService.js';
import { IExtensionRecommendationNotificationService } from '../../../../platform/extensionRecommendations/common/extensionRecommendations.js';
import { IExtensionRecommendationsService } from '../../../services/extensionRecommendations/common/extensionRecommendations.js';
import { IExtensionsWorkbenchService } from '../../extensions/common/extensions.js';
import { IInteractiveDocumentService, InteractiveDocumentService } from '../../interactive/browser/interactiveDocumentService.js';
import { IInteractiveHistoryService, InteractiveHistoryService } from '../../interactive/browser/interactiveHistoryService.js';
import { ILanguageModelIgnoredFilesService, LanguageModelIgnoredFilesService } from '../../chat/common/ignoredFiles.js';
import { ILanguageModelStatsService, LanguageModelStatsService } from '../../chat/common/languageModelStats.js';
import { ILanguageModelToolsConfirmationService } from '../../chat/common/tools/languageModelToolsConfirmationService.js';
import { ILanguageModelToolsService } from '../../chat/common/tools/languageModelToolsService.js';
import { ILanguageModelsConfigurationService } from '../../chat/common/languageModelsConfiguration.js';
import { ILanguageModelsService, LanguageModelsService } from '../../chat/common/languageModels.js';
import { IMcpDevModeDebugging, McpDevModeDebugging } from '../../mcp/common/mcpDevMode.js';
import { IMcpElicitationService, IMcpSamplingService, IMcpService, IMcpWorkbenchService } from '../../mcp/common/mcpTypes.js';
import { IMcpRegistry } from '../../mcp/common/mcpRegistryTypes.js';
import { IMcpSandboxService, McpSandboxService } from '../../mcp/common/mcpSandboxService.js';
import { INotebookCellOutlineDataSourceFactory, NotebookCellOutlineDataSourceFactory } from '../../notebook/browser/viewModel/notebookOutlineDataSourceFactory.js';
import { INotebookCellStatusBarService } from '../../notebook/common/notebookCellStatusBarService.js';
import { INotebookEditorModelResolverService } from '../../notebook/common/notebookEditorModelResolverService.js';
import { INotebookEditorService } from '../../notebook/browser/services/notebookEditorService.js';
import { INotebookEditorWorkerService } from '../../notebook/common/services/notebookWorkerService.js';
import { INotebookExecutionService } from '../../notebook/common/notebookExecutionService.js';
import { INotebookExecutionStateService } from '../../notebook/common/notebookExecutionStateService.js';
import { INotebookKernelHistoryService, INotebookKernelService } from '../../notebook/common/notebookKernelService.js';
import { INotebookKeymapService } from '../../notebook/common/notebookKeymapService.js';
import { INotebookLoggingService } from '../../notebook/common/notebookLoggingService.js';
import { INotebookOutlineEntryFactory, NotebookOutlineEntryFactory } from '../../notebook/browser/viewModel/notebookOutlineEntryFactory.js';
import { INotebookRendererMessagingService } from '../../notebook/common/notebookRendererMessagingService.js';
import { INotebookService } from '../../notebook/common/notebookService.js';
import { IPlanReviewFeedbackService, PlanReviewFeedbackService } from '../../chat/browser/planReviewFeedback/planReviewFeedbackService.js';
import { IPluginGitService } from '../../chat/common/plugins/pluginGitService.js';
import { IPluginInstallService } from '../../chat/common/plugins/pluginInstallService.js';
import { IPluginMarketplaceService, PluginMarketplaceService } from '../../chat/common/plugins/pluginMarketplaceService.js';
import { IPromptsService } from '../../chat/common/promptSyntax/service/promptsService.js';
import { ISessionChatPillVisibilityService, SessionChatPillVisibility } from '../../chat/common/sessionChatPills.js';
import { ISessionSummaryHoverService, SessionSummaryHoverService } from '../../chat/browser/agentSessions/sessionSummaryHoverService.js';
import { IShareService } from '../../share/common/share.js';
import { ITestCoverageService, TestCoverageService } from '../../testing/common/testCoverageService.js';
import { ITestExplorerFilterState, TestExplorerFilterState } from '../../testing/common/testExplorerFilterState.js';
import { ITestProfileService, TestProfileService } from '../../testing/common/testProfileService.js';
import { ITestResultService, TestResultService } from '../../testing/common/testResultService.js';
import { ITestResultStorage, TestResultStorage } from '../../testing/common/testResultStorage.js';
import { ITestService } from '../../testing/common/testService.js';
import { ITestingContinuousRunService, TestingContinuousRunService } from '../../testing/common/testingContinuousRunService.js';
import { ITestingDecorationsService } from '../../testing/common/testingDecorations.js';
import { ITestingPeekOpener } from '../../testing/common/testingPeekOpener.js';
import { IToolResultCompressor } from '../../chat/common/tools/toolResultCompressor.js';
import { IVoiceChatService, VoiceChatService } from '../../chat/common/voiceChatService.js';
import { IVoiceCodeTranscriptionClient, VoiceCodeTranscriptionClient } from '../../chat/browser/speechToText/voiceCodeTranscriptionClient.js';
import { IWorkbenchMcpGatewayService } from '../../mcp/common/mcpGatewayService.js';
import { IWorkspacePluginSettingsService, WorkspacePluginSettingsService } from '../../chat/common/plugins/workspacePluginSettingsService.js';
import { InstantiationType, registerSingleton } from '../../../../platform/instantiation/common/extensions.js';
import { LanguageModelToolsConfirmationService } from '../../chat/browser/tools/languageModelToolsConfirmationService.js';
import { LanguageModelToolsService } from '../../chat/browser/tools/languageModelToolsService.js';
import { LanguageModelsConfigurationService } from '../../chat/browser/languageModelsConfigurationService.js';
import { McpElicitationService } from '../../mcp/browser/mcpElicitationService.js';
import { McpRegistry } from '../../mcp/common/mcpRegistry.js';
import { McpSamplingService } from '../../mcp/common/mcpSamplingService.js';
import { McpService } from '../../mcp/common/mcpService.js';
import { McpWorkbenchService } from '../../mcp/browser/mcpWorkbenchService.js';
import { NotebookCellStatusBarService } from '../../notebook/browser/services/notebookCellStatusBarServiceImpl.js';
import { NotebookEditorWidgetService } from '../../notebook/browser/services/notebookEditorServiceImpl.js';
import { NotebookEditorWorkerServiceImpl } from '../../notebook/browser/services/notebookWorkerServiceImpl.js';
import { NotebookExecutionService } from '../../notebook/browser/services/notebookExecutionServiceImpl.js';
import { NotebookExecutionStateService } from '../../notebook/browser/services/notebookExecutionStateServiceImpl.js';
import { NotebookKernelHistoryService } from '../../notebook/browser/services/notebookKernelHistoryServiceImpl.js';
import { NotebookKernelService } from '../../notebook/browser/services/notebookKernelServiceImpl.js';
import { NotebookKeymapService } from '../../notebook/browser/services/notebookKeymapServiceImpl.js';
import { NotebookLoggingService } from '../../notebook/browser/services/notebookLoggingServiceImpl.js';
import { NotebookModelResolverServiceImpl } from '../../notebook/common/notebookEditorModelResolverServiceImpl.js';
import { NotebookRendererMessagingService } from '../../notebook/browser/services/notebookRendererMessagingServiceImpl.js';
import { NotebookService } from '../../notebook/browser/services/notebookServiceImpl.js';
import { PluginInstallService } from '../../chat/browser/pluginInstallService.js';
import { PromptsService } from '../../chat/common/promptSyntax/service/promptsServiceImpl.js';
import { QuickChatService } from '../../chat/browser/widgetHosts/chatQuick.js';
import { ShareService } from '../../share/browser/shareService.js';
import { TestService } from '../../testing/common/testServiceImpl.js';
import { TestingDecorationService } from '../../testing/browser/testingDecorations.js';
import { TestingPeekOpener } from '../../testing/browser/testingOutputPeek.js';
import { ToolResultCompressorService } from '../../chat/browser/tools/toolResultCompressorService.js';

registerSingleton(IChatResponseResourceFileSystemProvider, ChatResponseResourceFileSystemProvider, InstantiationType.Delayed);
registerSingleton(IChatSpeechToTextService, ChatSpeechToTextService, InstantiationType.Delayed);
registerSingleton(IVoiceCodeTranscriptionClient, VoiceCodeTranscriptionClient, InstantiationType.Delayed);
registerSingleton(IChatTransferService, ChatTransferService, InstantiationType.Delayed);
registerSingleton(IChatService, ChatService, InstantiationType.Delayed);
registerSingleton(IChatWidgetService, ChatWidgetService, InstantiationType.Delayed);
registerSingleton(ISessionChatPillVisibilityService, SessionChatPillVisibility, InstantiationType.Delayed);
registerSingleton(IChatPasteTargetService, ChatPasteTargetService, InstantiationType.Delayed);
registerSingleton(IChatSideChatService, ChatSideChatService, InstantiationType.Delayed);
registerSingleton(IChatRequestOriginService, ChatRequestOriginService, InstantiationType.Delayed);
registerSingleton(IChatModelFeedbackSurveyService, ChatModelFeedbackSurveyService, InstantiationType.Delayed);
registerSingleton(IChatPetService, ChatPetService, InstantiationType.Delayed);
registerSingleton(IChatPetWidgetService, ChatPetWidgetService, InstantiationType.Delayed);
registerSingleton(IQuickChatService, QuickChatService, InstantiationType.Delayed);
registerSingleton(IChatAccessibilityService, ChatAccessibilityService, InstantiationType.Delayed);
registerSingleton(IChatWidgetHistoryService, ChatWidgetHistoryService, InstantiationType.Delayed);
registerSingleton(ILanguageModelsConfigurationService, LanguageModelsConfigurationService, InstantiationType.Delayed);
registerSingleton(ILanguageModelsService, LanguageModelsService, InstantiationType.Delayed);
registerSingleton(ILanguageModelStatsService, LanguageModelStatsService, InstantiationType.Delayed);
registerSingleton(IChatSlashCommandService, ChatSlashCommandService, InstantiationType.Delayed);
registerSingleton(IChatAgentService, ChatAgentService, InstantiationType.Delayed);
registerSingleton(IChatAgentNameService, ChatAgentNameService, InstantiationType.Delayed);
registerSingleton(IChatVariablesService, ChatVariablesService, InstantiationType.Delayed);
registerSingleton(IAgentPluginService, AgentPluginService, InstantiationType.Delayed);
registerSingleton(IPluginMarketplaceService, PluginMarketplaceService, InstantiationType.Delayed);
registerSingleton(IWorkspacePluginSettingsService, WorkspacePluginSettingsService, InstantiationType.Delayed);
registerSingleton(IAgentPluginRepositoryService, AgentPluginRepositoryService, InstantiationType.Delayed);
registerSingleton(IPluginGitService, BrowserPluginGitCommandService, InstantiationType.Delayed);
registerSingleton(IPluginInstallService, PluginInstallService, InstantiationType.Delayed);
registerSingleton(ILanguageModelToolsService, LanguageModelToolsService, InstantiationType.Delayed);
registerSingleton(IToolResultCompressor, ToolResultCompressorService, InstantiationType.Delayed);
registerSingleton(ILanguageModelToolsConfirmationService, LanguageModelToolsConfirmationService, InstantiationType.Delayed);
registerSingleton(IChatToolRiskAssessmentService, ChatToolRiskAssessmentService, InstantiationType.Delayed);
registerSingleton(IChatGoalSummaryService, ChatGoalSummaryService, InstantiationType.Delayed);
registerSingleton(IChatSubmitRequestHandlerService, ChatSubmitRequestHandlerService, InstantiationType.Delayed);
registerSingleton(IVoiceChatService, VoiceChatService, InstantiationType.Delayed);
registerSingleton(IChatCodeBlockContextProviderService, ChatCodeBlockContextProviderService, InstantiationType.Delayed);
registerSingleton(ICodeMapperService, CodeMapperService, InstantiationType.Delayed);
registerSingleton(IChatEditingService, ChatEditingService, InstantiationType.Delayed);
registerSingleton(IChatMarkdownAnchorService, ChatMarkdownAnchorService, InstantiationType.Delayed);
registerSingleton(IAgentNetworkFilterService, AgentNetworkFilterService, InstantiationType.Delayed);
registerSingleton(ILanguageModelIgnoredFilesService, LanguageModelIgnoredFilesService, InstantiationType.Delayed);
registerSingleton(IPromptsService, PromptsService, InstantiationType.Delayed);
registerSingleton(ICustomizationMigrationService, CustomizationMigrationService, InstantiationType.Delayed);
registerSingleton(IChatContextPickService, ChatContextPickService, InstantiationType.Delayed);
registerSingleton(IChatModeService, ChatModeService, InstantiationType.Delayed);
registerSingleton(IChatAttachmentResolveService, ChatAttachmentResolveService, InstantiationType.Delayed);
registerSingleton(IChatAttachmentWidgetRegistry, ChatAttachmentWidgetRegistry, InstantiationType.Delayed);
registerSingleton(IChatTodoListService, ChatTodoListService, InstantiationType.Delayed);
registerSingleton(IChatArtifactsService, ChatArtifactsService, InstantiationType.Delayed);
registerSingleton(IChatOutputRendererService, ChatOutputRendererService, InstantiationType.Delayed);
registerSingleton(IChatLayoutService, ChatLayoutService, InstantiationType.Delayed);
registerSingleton(IPlanReviewFeedbackService, PlanReviewFeedbackService, InstantiationType.Delayed);
registerSingleton(IChatTipService, ChatTipService, InstantiationType.Delayed);
registerSingleton(IChatDebugService, ChatDebugServiceImpl, InstantiationType.Delayed);
registerSingleton(IChatImageCarouselService, ChatImageCarouselService, InstantiationType.Delayed);
registerSingleton(IAgentHostImportConversationStore, AgentHostImportConversationStore, InstantiationType.Delayed);
registerSingleton(ISessionSummaryHoverService, SessionSummaryHoverService, InstantiationType.Delayed);
registerSingleton(IChatResponseFileChangesService, EditorChatResponseFileChangesService, InstantiationType.Delayed);
registerSingleton(ITestService, TestService, InstantiationType.Delayed);
registerSingleton(ITestResultStorage, TestResultStorage, InstantiationType.Delayed);
registerSingleton(ITestProfileService, TestProfileService, InstantiationType.Delayed);
registerSingleton(ITestCoverageService, TestCoverageService, InstantiationType.Delayed);
registerSingleton(ITestingContinuousRunService, TestingContinuousRunService, InstantiationType.Delayed);
registerSingleton(ITestResultService, TestResultService, InstantiationType.Delayed);
registerSingleton(ITestExplorerFilterState, TestExplorerFilterState, InstantiationType.Delayed);
registerSingleton(ITestingPeekOpener, TestingPeekOpener, InstantiationType.Delayed);
registerSingleton(ITestingDecorationsService, TestingDecorationService, InstantiationType.Delayed);
registerSingleton(IMcpRegistry, McpRegistry, InstantiationType.Delayed);
registerSingleton(IMcpSandboxService, McpSandboxService, InstantiationType.Delayed);
registerSingleton(IMcpService, McpService, InstantiationType.Delayed);
registerSingleton(IMcpWorkbenchService, McpWorkbenchService, InstantiationType.Delayed);
registerSingleton(IMcpDevModeDebugging, McpDevModeDebugging, InstantiationType.Delayed);
registerSingleton(IMcpSamplingService, McpSamplingService, InstantiationType.Delayed);
registerSingleton(IMcpElicitationService, McpElicitationService, InstantiationType.Delayed);
registerSingleton(IWorkbenchMcpGatewayService, BrowserMcpGatewayService, InstantiationType.Delayed);
registerSingleton(IExtensionsWorkbenchService, ExtensionsWorkbenchService, InstantiationType.Delayed /* Auto updates extensions */);
registerSingleton(IExtensionRecommendationNotificationService, ExtensionRecommendationNotificationService, InstantiationType.Delayed);
registerSingleton(IExtensionRecommendationsService, ExtensionRecommendationsService, InstantiationType.Delayed /* Prompts recommendations in the background */);
registerSingleton(INotebookService, NotebookService, InstantiationType.Delayed);
registerSingleton(INotebookEditorWorkerService, NotebookEditorWorkerServiceImpl, InstantiationType.Delayed);
registerSingleton(INotebookEditorModelResolverService, NotebookModelResolverServiceImpl, InstantiationType.Delayed);
registerSingleton(INotebookCellStatusBarService, NotebookCellStatusBarService, InstantiationType.Delayed);
registerSingleton(INotebookEditorService, NotebookEditorWidgetService, InstantiationType.Delayed);
registerSingleton(INotebookKernelService, NotebookKernelService, InstantiationType.Delayed);
registerSingleton(INotebookKernelHistoryService, NotebookKernelHistoryService, InstantiationType.Delayed);
registerSingleton(INotebookExecutionService, NotebookExecutionService, InstantiationType.Delayed);
registerSingleton(INotebookExecutionStateService, NotebookExecutionStateService, InstantiationType.Delayed);
registerSingleton(INotebookRendererMessagingService, NotebookRendererMessagingService, InstantiationType.Delayed);
registerSingleton(INotebookKeymapService, NotebookKeymapService, InstantiationType.Delayed);
registerSingleton(INotebookLoggingService, NotebookLoggingService, InstantiationType.Delayed);
registerSingleton(INotebookCellOutlineDataSourceFactory, NotebookCellOutlineDataSourceFactory, InstantiationType.Delayed);
registerSingleton(INotebookOutlineEntryFactory, NotebookOutlineEntryFactory, InstantiationType.Delayed);
registerSingleton(IAgentSessionsService, AgentSessionsService, InstantiationType.Delayed);
registerSingleton(IShareService, ShareService, InstantiationType.Delayed);
registerSingleton(IInteractiveHistoryService, InteractiveHistoryService, InstantiationType.Delayed);
registerSingleton(IInteractiveDocumentService, InteractiveDocumentService, InstantiationType.Delayed);
